# itk-version: 1.0.0
version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - prims
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  prims:
    image: stoplight/prism:4
    networks:
      - app
    ports:
      - "4010"
    volumes:
      - ${PWD}:/api
    command:
      mock -p 4010 --host 0.0.0.0 /api/reference/OS2Display.v1.yaml
