# itk-version: 1.0.0
version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - imposter
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  imposter:
    image: outofcoffee/imposter-openapi:beta
    networks:
      - app
    ports:
      - '8080'
    volumes:
      - ${PWD}/config:/opt/imposter/config:ro
      - ${PWD}:/opt/imposter/config/api:ro

